/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class API_PASS_SECRET_MAIN_pass */

#ifndef _Included_API_PASS_SECRET_MAIN_pass
#define _Included_API_PASS_SECRET_MAIN_pass
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     API_PASS_SECRET_MAIN_pass
 * Method:    validatePasswordWithCpp
 * Signature: (Ljava/lang/String;)Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_API_1PASS_1SECRET_MAIN_1pass_validatePasswordWithCpp
  (JNIEnv *, jclass, jstring);

/*
 * Class:     API_PASS_SECRET_MAIN_pass
 * Method:    cppPass
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_API_1PASS_1SECRET_MAIN_1pass_cppPass
  (JNIEnv *, jclass);

#ifdef __cplusplus
}
#endif
#endif
